### ISSUE TITLE
Missing `l` in docs

### ISSUE THREAD

**Issue by FanaHOVA** [digma-ai/otel-sample-fastapi-singleservice#2]
In the Python quick start guide, the install command is missing a `l` in the `.yml` extension:

```
curl https://get.digma.ai/ --output docker-compose.ym
```

URL: https://digma.ai/python-quick-start-guide/

Didn't see the docs hosted anywhere, so couldn't find a way to open a PR for it myself. Outside of that I got this sample repo running and Digma appearing without issues, looks slick!

**Comment by doppleware** [comment]
Thanks for the feedback! This was indeed omitted by mistake in the Python version of the quick start.
Should now be fixed.

Thanks!
